# Generated by Django 4.0.5 on 2022-07-04 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('is_processeed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_of_payment', to='mine_mgt.mine')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=250)),
                ('reason', models.CharField(max_length=250)),
                ('is_processeed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='mine_mgt.mine')),
                ('proof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='mine_mgt.proof')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('size_approximation', models.CharField(max_length=250)),
                ('date_applied', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('forfeit', 'Forfeited'), ('active', 'Active')], default='pending_approval', max_length=30)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='mine_mgt.mine')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
