# Generated by Django 4.0.5 on 2022-07-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mine',
            name='balance',
            field=models.CharField(default=33343, max_length=250),
            preserve_default=False,
        ),
    ]
