# Generated by Django 4.0.5 on 2022-07-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine_mgt', '0002_mine_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='location',
            field=models.CharField(default=2232, max_length=250),
            preserve_default=False,
        ),
    ]
