# Generated by Django 4.0.5 on 2022-07-04 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mine_mgt', '0004_alter_mine_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='mine',
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(default=122, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proof',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_of_payment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Mine',
        ),
    ]
