# Generated by Django 4.0.5 on 2022-07-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine_mgt', '0006_alter_proof_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proof',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
